#ifndef DISPLAYGRAPHICSCODEGENERATORLIB_GLOBAL_H
#define DISPLAYGRAPHICSCODEGENERATORLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DISPLAYGRAPHICSCODEGENERATORLIB_LIBRARY)
#  define DISPLAYGRAPHICSCODEGENERATORLIB_EXPORT Q_DECL_EXPORT
#else
#  define DISPLAYGRAPHICSCODEGENERATORLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYGRAPHICSCODEGENERATORLIB_GLOBAL_H
